"""Recurrent modular-squaring model for One Layer Deeper.

Mathematical premise
--------------------
Every target is  result = x^(2^T) mod N  with the one-step recurrence

        result(T+1) = result(T)^2 mod N ,      result(0) = x .

So the whole certified-depth ladder T = 1,2,4,8,16,32,64 is generated by
iterating a *single* map, the squaring endomorphism  s_N(u) = u^2 mod N, of the
unit group.  If a model computes s_N exactly on the residues its computation
visits, then iterating that map is exact at every depth -- certification
extrapolates in T for free (see ANALYSIS.md, Claim 1).

Architecture
------------
This is the literal "one layer deeper" model: a bidirectional encoder reads the
prompt (N, x, T) once, a single WEIGHT-TIED recurrent cell g is applied T times
(adaptive computation depth = T, allowed by rule 4), and a place-value decoder
reads the answer digits off the final state, tail-aligned to the prompt end.

Because the cell is tied and the training data spans several T, endpoint
supervision at different composition depths pushes the shared cell toward the
true single-step dynamics (ANALYSIS.md, Claim 2').  Correctness then propagates
through the iteration, so depth generalizes far beyond the trained T.

Rule compliance: weights are randomly initialized and trained end to end;
no weights are loaded; every logit is produced by learned parameters with an
unbroken autograd path from the loss; the only non-differentiable, input
dependent quantity is the recurrence depth, which rule 4 explicitly permits as
adaptive computation.  Nothing here hard-codes modular arithmetic; the squaring
map is learned.
"""
from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import Tensor, nn

from benchmark import (
    ModelSpec,
    OptimizerBundle,
    OptimizerSpec,
    Submission,
    assert_model_state,
)

# --- token layout (public, from the dataset spec) ----------------------------
PAD, BOS, N_MARK, X_MARK, T_MARK, ANS, EOS = 0, 1, 2, 3, 4, 5, 6
DIGIT_OFFSET = 7  # digit d (0..9) has token id DIGIT_OFFSET + d

D_MODEL = 256
NUM_HEADS = 4
ENC_LAYERS = 3
MAX_ITERS = 64  # ceiling on recurrent depth (top of the T ladder)


class Config:
    def __init__(self, vocab_size: int, max_seq_len: int) -> None:
        self.vocab_size = vocab_size
        self.max_seq_len = max_seq_len


class RMSNorm(nn.Module):
    def __init__(self, width: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(width))

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.shape[-1],), self.weight)


class Block(nn.Module):
    """Bidirectional pre-norm attention + MLP block (padding-masked)."""

    def __init__(self) -> None:
        super().__init__()
        self.attention_norm = RMSNorm(D_MODEL)
        self.qkv = nn.Linear(D_MODEL, 3 * D_MODEL)
        self.out = nn.Linear(D_MODEL, D_MODEL)
        self.mixer_norm = RMSNorm(D_MODEL)
        self.up = nn.Linear(D_MODEL, 4 * D_MODEL)
        self.down = nn.Linear(4 * D_MODEL, D_MODEL)

    def forward(self, x: Tensor, key_padding: Tensor | None) -> Tensor:
        residual = x
        h = self.attention_norm(x)
        batch, length, _ = h.shape
        q, k, v = self.qkv(h).chunk(3, dim=-1)
        q = q.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        k = k.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        v = v.view(batch, length, NUM_HEADS, -1).transpose(1, 2)
        mask = None
        if key_padding is not None:
            mask = key_padding[:, None, None, :].to(dtype=torch.bool)
        h = F.scaled_dot_product_attention(q, k, v, attn_mask=mask)
        h = h.transpose(1, 2).contiguous().view(batch, length, D_MODEL)
        x = residual + self.out(h)
        return x + self.down(F.gelu(self.up(self.mixer_norm(x))))


class SquaringCell(nn.Module):
    """The single tied cell iterated to realize repeated squaring.

    Gated residual update so that iterating it is numerically stable to depth 64
    and, at initialization, close to the identity (a no-op squaring)."""

    def __init__(self) -> None:
        super().__init__()
        self.norm = RMSNorm(D_MODEL)
        self.up = nn.Linear(D_MODEL, 4 * D_MODEL)
        self.down = nn.Linear(4 * D_MODEL, D_MODEL)
        self.gate = nn.Linear(D_MODEL, D_MODEL)

    def forward(self, z: Tensor) -> Tensor:
        h = self.norm(z)
        update = self.down(F.gelu(self.up(h)))
        gate = torch.sigmoid(self.gate(h))
        return z + gate * update


class Model(nn.Module):
    def __init__(self, spec: ModelSpec) -> None:
        super().__init__()
        self.config = Config(spec.vocab_size, spec.max_seq_len)
        self.token_embedding = nn.Embedding(spec.vocab_size, D_MODEL)
        self.position_embedding = nn.Embedding(spec.max_seq_len, D_MODEL)
        self.encoder = nn.ModuleList(Block() for _ in range(ENC_LAYERS))
        self.encoder_norm = RMSNorm(D_MODEL)
        self.cell = SquaringCell()  # one tied cell -> "one layer deeper"
        # place-value decoder: state + place index -> per-position digit logits
        self.place_embedding = nn.Embedding(spec.max_seq_len, D_MODEL)
        self.decoder_norm = RMSNorm(D_MODEL)
        self.decoder = nn.Sequential(
            nn.Linear(2 * D_MODEL, 4 * D_MODEL), nn.GELU(),
            nn.Linear(4 * D_MODEL, D_MODEL), nn.GELU(),
        )
        self.head = nn.Linear(D_MODEL, spec.vocab_size, bias=False)

    def _read_time_steps(self, input_ids: Tensor) -> int:
        """Recurrence depth = max T in the batch (adaptive computation, rule 4).

        T is encoded as the decimal digits after the T marker.  This only sets
        how many times the learned cell is applied; it never enters the logits.
        """
        max_t = 1
        ids = input_ids.tolist()
        for row in ids:
            digits, reading = [], False
            for tok in row:
                if tok == T_MARK:
                    reading = True
                    continue
                if reading:
                    if DIGIT_OFFSET <= tok < DIGIT_OFFSET + 10:
                        digits.append(tok - DIGIT_OFFSET)
                    else:
                        break
            if digits:
                value = 0
                for d in digits:
                    value = value * 10 + d
                max_t = max(max_t, value)
        return max(1, min(MAX_ITERS, max_t))

    def _row_time_steps(self, input_ids: Tensor) -> Tensor:
        out = []
        for row in input_ids.tolist():
            digits, reading = [], False
            for tok in row:
                if tok == T_MARK:
                    reading = True
                    continue
                if reading:
                    if DIGIT_OFFSET <= tok < DIGIT_OFFSET + 10:
                        digits.append(tok - DIGIT_OFFSET)
                    else:
                        break
            value = 0
            for d in digits:
                value = value * 10 + d
            out.append(max(1, min(MAX_ITERS, value if digits else 1)))
        return torch.tensor(out, device=input_ids.device, dtype=torch.long)

    def forward(
        self,
        input_ids: Tensor,
        attention_mask: Tensor | None = None,
    ) -> tuple[Tensor, None]:
        batch, length = input_ids.shape
        device = input_ids.device
        key_padding = (
            attention_mask.bool() if attention_mask is not None else input_ids != PAD
        )

        positions = torch.arange(length, device=device)
        x = self.token_embedding(input_ids) + self.position_embedding(positions)
        for block in self.encoder:
            x = block(x, key_padding)
        x = self.encoder_norm(x)

        # Pool the prompt into a value state z0 representing x (masked mean).
        mask_f = key_padding.float().unsqueeze(-1)
        z = (x * mask_f).sum(1) / mask_f.sum(1).clamp_min(1.0)

        # Apply the tied squaring cell.  All rows iterate to the batch max T;
        # each row's state is frozen once its own T is reached (equivalent to
        # per-row depth = T, but batched).  Gradient flows through every used
        # application of the shared cell.
        steps = self._read_time_steps(input_ids)
        row_t = self._row_time_steps(input_ids)
        for i in range(1, steps + 1):
            z_next = self.cell(z)
            active = (row_t >= i).float().unsqueeze(-1)
            z = active * z_next + (1.0 - active) * z

        # Place-value decode, tail-aligned to each row's true prompt end.
        lengths = key_padding.long().sum(1)  # [B]
        idx = torch.arange(length, device=device).unsqueeze(0)  # [1, L]
        place = (lengths.unsqueeze(1) - 1 - idx).clamp_min(0)  # [B, L]
        place_emb = self.place_embedding(place.clamp_max(self.config.max_seq_len - 1))
        z_broadcast = z.unsqueeze(1).expand(-1, length, -1)
        decoded = self.decoder(
            torch.cat([self.decoder_norm(z_broadcast), place_emb], dim=-1)
        )
        logits = self.head(decoded)
        return logits, None


def build_model(spec: ModelSpec) -> Model:
    model = Model(spec)
    assert_model_state(model, spec)
    return model


def build_optimizer(model: nn.Module, spec: OptimizerSpec) -> OptimizerBundle:
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=2e-3,
        betas=(0.9, 0.95),
        weight_decay=0.05,
        capturable=spec.device_type == "cuda",
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20_000)
    return OptimizerBundle(optimizer, scheduler=scheduler)


SUBMISSION = Submission(
    build_model=build_model,
    build_optimizer=build_optimizer,
    batch_size=512,
)
